version: '3.5'

networks:
  backend:
    driver: 'bridge'

services:
  php-fpm:
    build:
      context: php-fpm
    working_dir: /var/www
    volumes:
      - ../backend:/var/www
    networks:
      - backend

  nginx:
    build:
      context: nginx
    working_dir: /var/www
    volumes:
      - ../backend:/var/www
      - ./nginx/conf.d:/etc/nginx/conf.d
    ports:
      - "80:80"
    networks:
      - backend
    depends_on:
      - php-fpm

  pgsql:
    image: postgres:13.4-alpine3.14
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - ./.data/pgsql:/var/lib/postgresql/data
    networks:
      - backend
